version: '3.4'
services:
  shepherd-php:
    container_name: shepherd-php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: "${PWD}/database"
        target: "/var/www/html/database"